#!/bin/bash
cat << 'EOF'
Status: 200 OK
Content-Type: text/html

<!DOCTYPE html>
<html>
<head>
    <title>CGI Hello World</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; }
        h1 { color: #667eea; }
        .env { background: #f0f0f0; padding: 10px; margin: 10px 0; border-radius: 4px; font-family: monospace; }
    </style>
</head>
<body>
    <div class='container'>
        <h1>✨ CGI Script Executed Successfully!</h1>
        <p>This page was generated by a CGI script.</p>
        <h2>Environment Variables</h2>
        <div class='env'>
            REQUEST_METHOD: GET<br>
            SERVER_NAME: localhost<br>
            SERVER_PORT: 8000<br>
            REMOTE_ADDR: 127.0.0.1<br>
        </div>
    </div>
</body>
</html>
EOF

